### ISSUE TITLE
centos/postgresql-94-centos7 fails to start on OpenShift cluster

### ISSUE THREAD

**Issue by csrwng** [sclorg/postgresql-container#116]
Using the template from https://github.com/openshift/rails-ex, the postgresql db pod fails to start with the following error:

```
/usr/share/container-scripts/postgresql/common.sh: line 121: /var/lib/pgsql/passwd: Permission denied
```

**Comment by csrwng** [comment]
The image used by the example comes from the one defined in the openshift image streams file: https://github.com/openshift/origin/blob/master/examples/image-streams/image-streams-centos7.json
@bparees is that the right postgresql image?

**Comment by bparees** [comment]
that's the right image, and i just tried it and it worked fine for me, can you pull the latest centos/postgresql-94-centos7 image down?

**Comment by bparees** [comment]
`oc new-app https://raw.githubusercontent.com/openshift/rails-ex/master/openshift/templates/rails-postgresql.json`

is what i ran.

**Comment by csrwng** [comment]
@bparees I pulled this image fresh into a new VM, but I think I know what's going on. This likely one of those cases where the image will run fine on RHEL/Fedora but not on a non-RedHat OS.

**Comment by csrwng** [comment]
So running on the boot2docker OS, it looks like with an arbitrary uid, even though my gid is set to 0, I cannot write to the home directory where permissions are:
```
bash-4.2$ ls -al
total 12
drwxrwx---  4 postgres root 4096 May 17 14:40 .
```

**Comment by csrwng** [comment]
Actually setting the permissions to 777 on that directory doesn't help either. Maybe has something to do with how the image was built?

**Comment by bparees** [comment]
nothing magical about how that image is built, we aren't even squashing anymore.  can you build it yourself and see if the behavior is any different?

**Comment by csrwng** [comment]
I get the same behavior when built locally. However, if I chmod 777 the home directory right after creating it, then things work. Would that be an acceptable fix?

**Comment by bparees** [comment]
chmod 777 instead of chgrp/chmod g+rwx ?

i'd like to understand why, when you're a member of the root group, you can't write to a directory owned by the root group.

**Comment by csrwng** [comment]
doing additional testing to better understand the problem

**Comment by praiskup** [comment]
Can SELinux be the issue?

**Comment by bparees** [comment]
any results?

**Comment by csrwng** [comment]
will revisit this issue today. I want to get a set a reproducible steps before I ask the wider community for help.

**Comment by csrwng** [comment]
@bparees Latest update... 

The difference between a RHEL/Fedora docker and other Docker is that the permissions for the /var/lib/postgresql directory are different. On RHEL, the permissions are 775, on a Mac, they are 770.

There's something about the packages installed that causes this. If I remove the yum install from the Dockerfile, the permissions are the same on both OS's.

**Comment by bparees** [comment]
775 vs 770 still means you have group permission to write to it.

**Comment by praiskup** [comment]
> The difference between a RHEL/Fedora docker and other Docker is that the permissions for the /var/lib/postgresql directory are different. On RHEL, the permissions are 775, on a Mac, they are 770.

Seems like bug in Docker?  Can you send some links to bug-report(s)? (I would expect 770
unless there are some weird bind-mounts).  Also there is no '/var/lib/postgresql' but
/var/lib/pgsql, but that might be a typo.

**Comment by csrwng** [comment]
It does look like a bug in Docker. However, I wanted to narrow it down to a simple use case. So here's the simplest I could come up with. If a directory is created in one layer and it's owned by a particular group, and later that group (and mode) is changed in a following layer, a user doesn't have permission to write to that directory. 

```
FROM centos:centos7
RUN useradd test
RUN mkdir /var/lib/test && chown test:test /var/lib/test && chmod 700 /var/lib/test
RUN chgrp root /var/lib/test && chmod 770 /var/lib/test
```

```
$ docker run -ti -u 10000 testimage
bash-4.2$ touch /var/lib/test/test
touch: cannot touch '/var/lib/test/test': Permission denied
```

However, if the group and mode are changed all in the same layer as when the directory is created, then the permissions work:

```
FROM centos:centos7
RUN useradd test
RUN mkdir /var/lib/test && chown test:test /var/lib/test && chmod 700 /var/lib/test && \
    chgrp root /var/lib/test && chmod 770 /var/lib/test
```

```
$ docker run -ti -u 10000 testimage
bash-4.2$ touch /var/lib/test/test
```

**Comment by csrwng** [comment]
Docker issue https://github.com/docker/docker/issues/24660

**Comment by bparees** [comment]
and you only observe this on osx/boot2docker, not on fedora/rhel docker, right?

**Comment by csrwng** [comment]
Right

**Comment by praiskup** [comment]
Thanks @csrwng for taking care of this!

**Comment by GrahamDumpleton** [comment]
This would be similar to issue I reported back in 2014 with AUFS.

* https://github.com/docker/docker/issues/9547

They can't or don't want to fix it even though so many people have reported the same issue.

There just seems to be a known limitation with changing attributes on files in different layers when using AUFS.

**Comment by GrahamDumpleton** [comment]
We also had to use a workaround in Python S2I builder previously related to these sorts of problems with layers. Specifically, had to fiddle with permissions or something on the ``.pki`` directory in the home directory as would cause issues later on when doing stuff in later layer.

**Comment by GrahamDumpleton** [comment]
Is a change for this going to be implemented in the PostgreSQL image? Or is the stance being taken that this is a Docker bug and needs to be fixed in Docker?

There is a history of layer issues with AUFS not being being in Docker. I sort of recollect seeing a statement once that they don't regard AUFS as the preferred option in the long term and so aren't investing any time in fixing issues related to it. If we want a solution for this, fixing it in our image is going to be the quickest route.

**Comment by bparees** [comment]
I wasn't intending to work around it, if this is really a bug that affects all default OSX distributions, I would think Docker would be motivated to fix it.  But if we really think docker is going to ignore it, i'm not averse to the workaround described in https://github.com/sclorg/postgresql-container/issues/116#issuecomment-232845287

Will leave it up to @hhorak

**Comment by jorgemoralespou** [comment]
It's failing for me as well and we can't demo PostgreSQL properly on oc cluster

**Comment by GrahamDumpleton** [comment]
The other thing that I didn't realise initially was that it isn't just ``hostPath`` mounts that it fails with. Also fails with ``emptyDir``, which is what is used for ephemeral template. So can't demonstrate it at all, either ephemeral or persistent. Since going to be posting blog about using ``oc cluster up`` quite soon now, probably going to see this becoming a growing problem as people try ``oc cluster up``. Already seen one other person having  issue on sme list.

**Comment by praiskup** [comment]
@csrwng when you created the 'test' user in your example in comment 116, have you
somehow specified UID/GID?  I.e. does the `docker run ... -u 10000` command what we
expect it should?

**Comment by praiskup** [comment]
Ah, it is expected "test" user has UID different from 10000.

**Comment by praiskup** [comment]
I'm curious, what is different on `/var/lib/test` directory when you (a) create the directory
in two docker-build layers and (b) you create it in one?  That is, could you also post
`stat /var/lib/test/ && echo && id` output in both cases? @csrwng 

I know that BSD handle the group permissions a bit differently from Linux (from some POV),
I'm not an expert on Mac OS/BSD and I can not even test it ... but if this is something like
cross-kernel issue, I doubt PostgreSQL container is the right place to workaround such issues.

**Comment by csrwng** [comment]
@praiskup I doubt it has anything to do with the kernel. It's more an aufs storage driver issue. On Mac or Windows, BSD is not involved as they both use the Linux distro in the Docker VM.

**Comment by csrwng** [comment]
@praiskup as for the test ... the file permissions look exactly the same in both cases.

**Comment by bparees** [comment]
i'm working around this here:
https://github.com/sclorg/postgresql-container/pull/134

**Comment by praiskup** [comment]
@csrwng wrote
> @praiskup I doubt it has anything to do with the kernel. It's more an aufs storage driver issue. On Mac or Windows, BSD is not involved as they both use the Linux distro in the Docker VM.

Thanks, good to know :).

> @praiskup as for the test ... the file permissions look exactly the same in both cases.

Have you checked this During 'docker build', or after 'docker run'?  That would be really
weird if the permission/ownership bits were completely the same during container runtime
and kernel would apply different policies.
