### ISSUE TITLE
Allow remote connections for pg_basebackup

### ISSUE THREAD

**Issue by chrira** [sclorg/postgresql-container#157]
The file `openshift-custom-postgresql.conf.template` should be extended to allow remote connections for backups with the `pg_basebackup` tool.

Error Message:

> pg_basebackup: could not connect to server: FATAL: number of requested standby connections exceeds max_wal_senders (currently 0)

With this additional configuration, the backup works:

    max_wal_senders = 5
    wal_level = hot_standby
    archive_mode = on
    archive_command = '/bin/true'

**Comment by pkubatrh** [comment]
After https://github.com/sclorg/postgresql-container/pull/208 is merged in you will be able to extend the configuration file

**Comment by pkubatrh** [comment]
This should be fixed by #208 

Feel free to re-open if you run into any problems
