### ISSUE TITLE
Add PostGIS RPMs to the install??

### ISSUE THREAD

**Issue by znmeb** [sclorg/postgresql-container#159]
This is fairly easy and the code doesn't take up much space in the image. I can fork and pull request if you want this.

**Comment by praiskup** [comment]
@znmeb postgresql-container is built from SCLs, and AFAIK we don't have production ready PostGIS yet in e.g. https://copr.fedorainfracloud.org/coprs/rhscl/rh-postgresql94-el7/

**Comment by znmeb** [comment]
ah ... but I can use this image in a FROM in a Dockerfile and bring in the standard PostGIS RPMs from an external repo, can't it? I think there are RPMs on PostgreSQL project sites

**Comment by praiskup** [comment]
As long as major version number of PostgreSQL matches, it _could_ work -- but you'll need some manual tweaks (e.g. SCL's version of PostgreSQL tries to find modules (thus postgis, too) within non-default directory).

**Comment by praiskup** [comment]
"non-default directory" is wrong term, sorry, what I meant is "something else than %_libdir/pgsql"

**Comment by znmeb** [comment]
Bah ... for that much effort I'd rather just go with a source-to-image build of the whole stack

**Comment by praiskup** [comment]
You could possibly wait for SCLized PostGIS, or use 'FROM: fedora/postgresql' (non-scl).

**Comment by znmeb** [comment]
I don't want to mix Fedora and CentOS and I've been looking for a good excuse to learn S2I ;-)

**Comment by thesteve0** [comment]
If this image uses EPEL then we can just add the Postgis pieces like the crunchy people do:


https://github.com/thesteve0/crunchy-containers/blob/master/centos7/9.6/Dockerfile.postgres-gis.centos7#L35

What I am concerned about is how you both hard code user 26 - OpenShift will use a random userid instead
