### ISSUE TITLE
postgres 9.6

### ISSUE THREAD

**Issue by twk3** [sclorg/postgresql-container#161]
With postgres 9.6 being available, I have containers that are going from supporting 9.2 to 9.6. It would be great if there were also a 9.6 container we could use in openshift.

**Comment by praiskup** [comment]
Thanks for the report!

I plan to take a look at this, @pkubatrh @hhorak.  I guess we first need to have sclized version of postgresql (in copr, against centos) and then we need to add centos version of container. WDYT?

**Comment by akeum** [comment]
+1

**Comment by pkubatrh** [comment]
Postgresql version 9.6 has recently been added via https://github.com/sclorg/postgresql-container/pull/182 so I guess this can be closed.
