### ISSUE TITLE
PostgreSQL containers fail to start on Fedora 25

### ISSUE THREAD

**Issue by praiskup** [sclorg/postgresql-container#163]
```
$ docker run --rm -ti openshift/postgresql-92-centos7 
Warning: Can't detect memory limit from cgroups
Warning: Can't detect number of CPU cores from cgroups
/usr/share/container-scripts/postgresql/common.sh: line 9: MEMORY_LIMIT_IN_BYTES: unbound variable
```

**Comment by praiskup** [comment]
Probably some security feature kills this hack.  My original complaint was that this is not something to be done by container itself (some ugly heuristics) -- environment should set those options.

As a band-aid, we should use `${MEMORY_LIMIT_IN_BYTES-}`, and probably remove the hack completely?

**Comment by pkubatrh** [comment]
This seems to have happened because of a change in container-selinux policies, but is already fixed in the latest version of the package (container-selinux-2.10-1) so there is no need to hotfix this unless to make sure it does not happen in future.

**Comment by praiskup** [comment]
Because we have `set -e`, it still is an issue.  Could you cite the ticket related to container-selinux issue?

**Comment by pkubatrh** [comment]
Have not found a ticket related to this anywhere. I have just updated to the most recent version of the package and that fixed the issue for me.
My knowledge of selinux and its policies is quite limited but I think this is the upstream commit that modifies the access to cgroups files:
https://github.com/projectatomic/container-selinux/commit/c9829f9ea1542d876bc4641720c1a373db47ab20

**Comment by praiskup** [comment]
Ok, thanks for the info!  Seems like the recent update fixed my box too.
