### ISSUE TITLE
Image postgresql-94-rhel7 doesn't allow to change default log path for PostgreSQL database.

### ISSUE THREAD

**Issue by niconosenzo** [sclorg/postgresql-container#175]
Currently, PostgreSQL DB redirect logs to $pg_log path (/var/lib/pgsql/data/userdata/pg_log/*), and there is no variable that allows the user to change this value.

This behaviour would be very helpful in use cases (i.e.) where the DB logs want to be collected by the EFK stack within the default paths.

**Comment by niconosenzo** [comment]
Might we have a comment on this ?

**Comment by phracek** [comment]
This image has reached EOL. In case of the issue is still valid feel free to re-open this issue.
