### ISSUE TITLE
Bad UX for commands

### ISSUE THREAD

**Issue by stevekuznetsov** [sclorg/postgresql-container#190]
When running a shell to pick up the SCL environment I always get these two log lines in my pods:

```
sh: cannot set terminal process group (-1): Inappropriate ioctl for
device sh: no job control in this shell
```

This looks bad but is as far as I can tell benign. In any case this should be at least not shown to the user if it's not an error they should care about.

**Comment by praiskup** [comment]
Thanks for the report. @stevekuznetsov how do you run the image?

**Comment by stevekuznetsov** [comment]
I'm running the image as an OpenShift `Pod` and running `/bin/sh -i -c ...` to enable the SCL variables.

**Comment by praiskup** [comment]
Unfortunately, `/bin/sh` doesn't do the trick - `/bin/bash` should.

**Comment by praiskup** [comment]
Wrong, sorry.  This IMO happens because you run interactive shell without terminal attached (if you've been using docker, you would be missing the `-t` option).

Is switch to plain (non-interactive) bash an alternative for you?

**Comment by pkubatrh** [comment]
@stevekuznetsov ping ^

**Comment by stevekuznetsov** [comment]
@bparees have you guys ever tried not using the `-i` flag in these preambles?

**Comment by bparees** [comment]
@stevekuznetsov pretty sure that causes the SCL enablement scripting, which is part of bash env vars, to not get invoked.

**Comment by stevekuznetsov** [comment]
@pkubatrh @praiskup have _y'all_ tried without an interactive shell?

**Comment by pkubatrh** [comment]
AFAIK we are already making sure the collections are properly enabled even when not using interactive shell https://github.com/sclorg/postgresql-container/blob/master/9.5/Dockerfile.rhel7#L67

```
$ docker run rhscl/postgresql-95-rhel7 bash -c "scl_enabled rh-postgresql95 && echo Enabled"
Enabled
```

**Comment by praiskup** [comment]
> @stevekuznetsov pretty sure that causes the SCL enablement scripting, which is part of bash env vars, to not get invoked.

It's not, per e.g. fedora container:
```
$ docker run --rm  fedora /bin/sh -i
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
sh-4.4# exit
```

That message occurs because you explicitly requested `sh -i`, but you haven't attached terminal properly to it.

**Comment by praiskup** [comment]
> @pkubatrh @praiskup have y'all tried without an interactive shell?

I was actually asking you to **not** start that in interactive shell :). 

$ docker run --rm  centos/postgresql-95-centos7 sh -c "psql --version"
psql (PostgreSQL) 9.5.7
