### ISSUE TITLE
Provide better error message when validation of required env var fails

### ISSUE THREAD

**Issue by mfojtik** [sclorg/postgresql-container#191]
When validation of `POSTGRESQL_USER` fail, because user set it to 'foo-bar' you get this:

```
For general container run, you must either specify the following environment
variables:
  POSTGRESQL_USER (regex: '^[a-zA-Z_][a-zA-Z0-9_]*$')
  POSTGRESQL_PASSWORD (regex: '^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$')
  POSTGRESQL_DATABASE (regex: '^[a-zA-Z_][a-zA-Z0-9_]*$')
Or the following environment variable:
  POSTGRESQL_ADMIN_PASSWORD (regex: '^[a-zA-Z0-9_~!@#$%^&*()-=<>,.?;:|]+$')
Or both.
```

Instead you should get something like `Invalid POSTGRESQL_USER value: foo-bar (regexp)`

**Comment by erenfro** [comment]
Or even better, since PostgreSQL accepts dashes in the username in this scenario, also accept those as well as part of the regex validation.

**Comment by mfojtik** [comment]
@hhorak @praiskup FYI

**Comment by praiskup** [comment]
Thanks for the report, good point.

Both of the issues (error reporting and wrong regexp) would disappear if we dropped the regex checking, and delegate the validation to postgresql itself.

**Comment by hhorak** [comment]
I think the regexps were invented also for preventing SQL injection. But I agree that the current regexps might be too restrictive.

**Comment by praiskup** [comment]
The `psql --variable` should be answer for SQL injection, but we need to have a closer look, thanks for the reminder!

**Comment by soltysh** [comment]
I'm trying to run 
```
docker run -p 5432:5432 -e POSTGRESQL_USER=13eewfsd23rwef23re -e POSTGRESQL_PASSWORD=wewsfsd234eewdsa -e POSTGRESQL_DATABASE=blast_image docker.io/centos/postgresql-95-centos7
``` 
and that fails with exactly the same error. Now how should I know what's actually wrong?

**Comment by soltysh** [comment]
Nvmd, I see I didn't fit the regex 🤦‍♂️

**Comment by praiskup** [comment]
Somewhat controversial #236, fyi.

**Comment by pkubatrh** [comment]
Since we leave the username/password checks to postgresql now (#236) I believe this can be closed.
