### ISSUE TITLE
Fedora dockefile

### ISSUE THREAD

**Issue by praiskup** [sclorg/postgresql-container#200]
It would be nice to have fedora dockerfile here, too.  Just to not loose the track of Fedora's image.

Fedora's image is basically the same what we have here in sclorg, but due to incompatible packaging techniques (scl/non-scl) we can not simply sync the scripts into Fedora's dist-git (otherwise for example the pg_upgrade feature won't work).

**Comment by praiskup** [comment]
@mkutlak fyi

**Comment by pkubatrh** [comment]
Fedora Dockerfile added via https://github.com/sclorg/postgresql-container/commit/87b7fdc85553a76dba497dbb6b74bce135b839e0 so I guess this can be closed.
