### ISSUE TITLE
postGIS extensions unavailable in the postgresql image 

### ISSUE THREAD

**Issue by bparees** [sclorg/postgresql-container#225]
The postGIS extension is available for use with the build of postgresql in Openshift Online:

```
CREATE EXTENSION postgis;
```

It would be nice to have the same default set of extensions available for v3 users as well.

(this issue copied from https://github.com/openshift/origin/issues/6745)

**Comment by AuthorProxy** [comment]
still no news?

**Comment by bparees** [comment]
@hhorak @pkubatrh @praiskup bump

**Comment by pkubatrh** [comment]
afaik there is still no progress on getting postgis into SCLs which is a prerequisite for adding it into the container image

**Comment by praiskup** [comment]
Adding PostGIS to SCL is tracked in [this bug](https://bugzilla.redhat.com/1008506)

**Comment by hhorak** [comment]
At this point, there are still no concrete plans to add PostGIS into RHSCL, sorry.
