### ISSUE TITLE
random hang in yum-utils installation?

### ISSUE THREAD

**Issue by praiskup** [sclorg/postgresql-container#238]
CI hangs sometimes on:
```
09:17:45  Fingerprint: 43a6 e49c 4a38 f4be 9abf 2a53 4568 9c88 2fa6 58e0
09:17:45  Package    : redhat-release-server-7.4-18.el7.x86_64 (@anaconda/7.4)
09:17:45  From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
09:17:45 [0mRunning transaction check
09:17:45 Running transaction test
09:17:45 Transaction test succeeded
09:17:45 Running transaction
09:17:46   Updating   : yum-utils-1.1.31-45.el7.noarch                               1/2 
```
https://coreservices-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhscl-images-postgresql-rh-openshift/41/console

We should debug what's going on there.

**Comment by praiskup** [comment]
A bit different hang https://coreservices-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhscl-images-postgresql-rh/317/consoleText

**Comment by praiskup** [comment]
I added request to enlarge RHEL's VM ram to 4GB (merge request 14), could help.

**Comment by omron93** [comment]
The first hang is quite often. Rebuild in most cases helps...

RAM could be a problem. I was also thinking if there could be some subscription magic after package cleanup... but don't know yum details, so it's only guess.

**Comment by praiskup** [comment]
Did not happen to me for quite some time, I guess the 4G RAM helped..  any votes against closing this?

**Comment by omron93** [comment]
Same for me. Thanks for the fix.
