### ISSUE TITLE
Wrong split of image to clean up

### ISSUE THREAD

**Issue by lukaszachy** [sclorg/postgresql-container#246]
In image cleanup, name of the image is split on ':' and it tries to delete two invalid parts. E.g.

ct_path_foreach rhscl/postgresql-94-rhel7:9.4-10-testapp_whj574flis cleanup_image
docker rmi -f rhscl/postgresql-94-rhel7
docker rmi -f 9.4-10-testapp_whj574flis

It should delete only one image of name "rhscl/postgresql-94-rhel7:9.4-10-testapp_whj574flis"

**Comment by pkubatrh** [comment]
Thanks for looking into this!

Probably not a good idea to use `ct_path_foreach` for something that is not a path...

**Comment by praiskup** [comment]
Yes, it would be nice if we could (somehow) define the separator to different character?
