### ISSUE TITLE
RHEL CI -- test against the latest image built by `s2i-base-container` CI

### ISSUE THREAD

**Issue by praiskup** [sclorg/postgresql-container#260]
It is really painful to wait till fixes in s2i-base take the effect https://github.com/sclorg/s2i-base-container/pull/159

It would be nice if we pushed the s2i-base image RHEL from CI somewhere, and tested layered images against that.

**Comment by praiskup** [comment]
work-around could be to move the "prepare yum repo" script into common scripts.

**Comment by omron93** [comment]
Good point.
Because we almost every time release (rebase to upstream) all images together, so there is no reason to test changes to already released s2i-base.

I'll try change CI to work this way. (probably next week)

**Comment by pkubatrh** [comment]
We already have a way to connect PRs together. This should be enough I hope.
