### ISSUE TITLE
404 on documentation

### ISSUE THREAD

**Issue by faustool** [sclorg/postgresql-container#262]
All the links to the Blog, including https://github.com/sclorg/postgresql-container/blob/master/9.5 is returning 404. Please update your README with the new path.

**Comment by pkubatrh** [comment]
Thanks for the report.

This is fallout from #203. The sources are available at [1] for the time being but may not stay there for long as we are considering moving to a "generated sources" branch inside this repository.

[1]: https://github.com/sclorg/postgresql-container-generated
