### ISSUE TITLE
Error with set_passwords.sh when restarting

### ISSUE THREAD

**Issue by tdudgeon** [sclorg/postgresql-container#297]
I've hit  problem in Openshift with the postgres pod failing to restart.
In a vanilla environment this works fine, but something's happened in my setup that now prevents the pod from restarting.
The Logs show:

```
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....LOG:  redirecting log output to logging collector process
HINT:  Future log output will appear in directory "pg_log".
........................................................... stopped waiting
server is still starting up
=> sourcing /usr/share/container-scripts/postgresql/start/set_passwords.sh ...
psql: FATAL:  the database system is starting up
```

This is with the centos/postgresql-95-centos7 image from Dockerhub.
Any ideas how to fix this?

**Comment by tdudgeon** [comment]
So I found out how to avoid this.
The server is started using `pg_ctl` with the `-w` flag to tell it to wait until started before completing.
By default it only waits for 60s (see https://www.postgresql.org/docs/9.5/static/app-pg-ctl.html) so what was happening was that it stopped waiting and the `set_passwords.sh` file was executed before the server was ready.
The quick fix is to set the `PGCTLTIMEOUT` environment variable to something longer (I used 300) to force it to wait for a longer period so that startup actually completed before moving or to running the set_passwords commands.

So maybe this suggests that the `PGCTLTIMEOUT` environment variable should be set to a suitable value in the image, or at least this should be documented somewhere?

**Comment by vutkin** [comment]
Hello, I have same issue.

I have notices it on postgresql 9.6 image.

When pod is crashed and restarted, postgresql starts recovery db process, but after 60 sec starts set_passwords.sh script and crash pod with error 2 (because postgresql is not started yet and set_passwords.sh can't reset passwords).

**Comment by praiskup** [comment]
The `run-postgresql` script contains `set -e`, and thus if  `pg_ctl -w` fails to wait for the server - it should `exit(1)` and thus the whole run-postgresql should be stopped (without continuing to `set_passwords.sh`).  Can you please check you don't disable the `set -e`?

**Comment by praiskup** [comment]
Helpful would be the log output from `CMD` like `bash -x /usr/bin/run-postgresql` - but please be careful to filter out all the passwords and other sensitive stuff.

**Comment by tdudgeon** [comment]
The `run-postgresql` script is not modified and so has `set -eu` at the top.
Maybe the `pg_ctl -w` command has exit code 0 when it times out?

**Comment by praiskup** [comment]
Don't you have some pre-start hooks? https://github.com/sclorg/postgresql-container/tree/generated/10#extending-image

**Comment by praiskup** [comment]
`........................................................... stopped waiting` I doubt it is possible to return non-zero exit status in this case, there's explicit `exit(1)` in pg_ctl code...

**Comment by praiskup** [comment]
Ok, you are right - pg_ctl in 9.6 has the following code - so actually doing `pg_ctl -w` is not reliable.  Thanks for the headsup.
```
 915         switch (test_postmaster_connection(pm_pid, false)) 
 916         {
 [snip]
 921             case PQPING_REJECT:
 922                 print_msg(_(" stopped waiting\n"));
 923                 print_msg(_("server is still starting up\n"));
 924                 break;
 925             case PQPING_NO_RESPONSE:
 926                 print_msg(_(" stopped waiting\n"));
 927                 write_stderr(_("%s: could not start server\n"
 928                                "Examine the log output.\n"),
 929                              progname);
 930                 exit(1);
 931                 break;
 [snip]
 937         }
```

**Comment by tdudgeon** [comment]
No prestart hooks. Just using the image as is.
