### ISSUE TITLE
Limit run_migration_test based on architecture

### ISSUE THREAD

**Issue by lukaszachy** [sclorg/postgresql-container#300]
run_migration_test tries to migrate from older images. However for non-intel architectures some images are not released and the test obviously fails (e.g. `no supported platform found in manifest list`).
It would be nice to be able to limit this test to architectures, where older images exist.

**Comment by pkubatrh** [comment]
Looking into this.
For some reason docker/podman is completely ok with pulling an x86_64 postgresql-92 image on a non-x86_64 host ...
