### ISSUE TITLE
Change default value of checkpoint_segments to at least 10 for better performance?

### ISSUE THREAD

**Issue by ghost** [sclorg/postgresql-container#318]
The Postgre [official document](https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server) recommends to set **checkpoint_segments** to at least 10, which improves the performance.
"Unless you're running on a very small configuration, you'll almost **certainly be better setting this to at least 10**, which also allows usefully increasing the completion target. ". 

I wonder if the default need to be changed for performance concern. Thanks.

**Comment by praiskup** [comment]
> I wonder if the default need to be changed for performance concern.

Maybe, does your databases suffer from too frequent checkpoints?

OpenShift (or its users) is known to be hard on PostgreSQL server (restarts, kills, ...), so crash-recovery is pretty normal thing ... and larger checkpoint_segments will probably prolong the crash-recovery during container start-up.
