### ISSUE TITLE
How to run and init postgresql before running container?

### ISSUE THREAD

**Issue by 40rn05lyv** [sclorg/postgresql-container#333]
Hi, I want to build my own image based on centos/postgresql-10-centos7 with following functionality:
1. Install, run and init postgresql
2. Run the installer for my app that requires connection to postgresql database.

I wrote the following Dockerfile:
FROM centos/postgresql-10-centos7
ADD myinstaller /tmp/
RUN /tmp/myinstaller

However, centos/postgresql-10-centos7 image is configured to run postgresql only when the container starts (cmd/entrypoint). Does anyone know how to run postgresql, wait for it to start and then run my own installer?

**Comment by pkubatrh** [comment]
Hi @40rn05lyv, the [command](https://github.com/sclorg/postgresql-container/blob/generated/10/Dockerfile#L91) that runs the postgresql server in the image is a [shell script](https://github.com/sclorg/postgresql-container/blob/generated/10/root/usr/bin/run-postgresql), so you should be able to run it as a step inside your `/tmp/myinstaller`

**Comment by pkubatrh** [comment]
Closing for now but feel free to re-open if you run into any issues.
