### ISSUE TITLE
centos/postgresql-12-centos7 image missing from dockerhub

### ISSUE THREAD

**Issue by thrix** [sclorg/postgresql-container#356]
SSIA, see https://hub.docker.com/search?q=centos%2Fpost&type=image

The image is not available

**Comment by pkubatrh** [comment]
Thanks for the issue. Seems like there was some problem during the push job, let me retry.

**Comment by pkubatrh** [comment]
Centos7-based Postgresql 12 image is now built, pushed and available in dockerhub:
https://hub.docker.com/r/centos/postgresql-12-centos7

**Comment by thrix** [comment]
@pkubatrh thanks very much!
