### ISSUE TITLE
Error building ubi8/postgres-9.6

### ISSUE THREAD

**Issue by jobcespedes** [sclorg/postgresql-container#358]
Is a subscription required to build ubi8/postgres-9.6? Below it is the build command and error:

```bash
podman build . -f Dockerfile.rhel8 -t ubi8/postgres-9.6
```

```bash
STEP 7: RUN yum -y module enable postgresql:9.6 &&     INSTALL_PKGS="rsync tar gettext bind-utils nss_wrapper postgresql-server postgresql-contrib" &&     yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum -y reinstall tzdata &&     yum -y clean all --enablerepo='*' &&     localedef -f UTF-8 -i en_US en_US.UTF-8 &&     test "$(id postgres)" = "uid=26(postgres) gid=26(postgres) groups=26(postgres)" &&     mkdir -p /var/lib/pgsql/data &&     /usr/libexec/fix-permissions /var/lib/pgsql /var/run/postgresql
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Red Hat Universal Base Image 8 (RPMs) - BaseOS  478 kB/s | 760 kB     00:01    
Red Hat Universal Base Image 8 (RPMs) - AppStre 2.2 MB/s | 3.1 MB     00:01    
Red Hat Universal Base Image 8 (RPMs) - CodeRea 7.8 kB/s | 9.1 kB     00:01    
Error: Problems in request:
missing groups or modules: postgresql:9.6
```

**Comment by pkubatrh** [comment]
@jobcespedes 
Yes a subscription is required to build the rhel8 version of postgresl 9.6. This is expected as it is not part of UBI. It is licensed via the regular rhel license (see [Dockerfile label](https://github.com/sclorg/postgresql-container/blob/generated/9.6/Dockerfile.rhel8#L33)).

**Comment by jobcespedes** [comment]
Thanks for the reply. I recently ran into UBIs. Much to learn here. 

I wanted to build a Postgresql ubi8 based but I believe there is currently no postgresql pkg in ubi8. I should use another base image, right?

**Comment by pkubatrh** [comment]
You can use ubi8 (and ubi8/s2i-core) as a base image for your builds, that should not be an issue.
If you build the postgresql image (on top of the base images above) on a subscribed rhel system the package manager inside the image will notice and you will have regular (non-ubi8 repositories) available as well.

**Comment by jobcespedes** [comment]
Thanks for the info. I read again [UBI FAQ](https://developers.redhat.com/articles/ubi-faq/). It is easier for me to understand now.
