### ISSUE TITLE
postgresql-11 support question

### ISSUE THREAD

**Issue by henrjk** [sclorg/postgresql-container#359]
I am wondering what the status of postgresql-11 is as it is currently not supported?
Do you look for contributions?
Are there known issues which caused this to be difficult?

**Comment by pkubatrh** [comment]
Hi @henrjk , thanks for the issue!
In rhel7 and rhel8 we skipped postgresql 11 and moved straight to 12. There are no plans I know of to provide postgresql 11 images for those OSs. Hence neither CentOS will be getting postgresql 11.

There is a postgresql 11 module in Fedora but the Dockerfile for Fedora version of postgresql stored in this repository is currently in a really sad state. Any contributions for this are very welcome!

**Comment by henrjk** [comment]
@pkubatrh thank you for the quick response.

Meanwhile it turned out that we will use version 10 for now and will likely migrate directly to 12 as well. 
As a result I am sorry to say that I will not be in a position to contribute support for version 11.
