### ISSUE TITLE
CentOS8 based images

### ISSUE THREAD

**Issue by Klaas-** [sclorg/postgresql-container#364]
Hi,
I saw the rhel8 ubi based postgresql images, are there any plans to also support centos8? Or can I use the ubi based images because they are licensed more liberal? The base image used for the rhel8 container is downloadable (https://access.redhat.com/containers/?tab=images&get-method=unauthenticated#/registry.access.redhat.com/ubi8/s2i-core) but the postgresql-10 one is not available without authentication (https://access.redhat.com/containers/?tab=images&get-method=unauthenticated#/registry.access.redhat.com/rhel8/postgresql-10)

Greetings
Klaas

**Comment by pkubatrh** [comment]
Hi @Klaas-, thanks for the question!

We definitely want to support centos8 images, but we are not there yet unfortunately.
I remember @phracek was looking at the possibilities of centos8 build recently, maybe he can add more details.
Also ping @fatherlinux for the possibility of adding postgresql and its dependencies to ubi8 instead. Though if I remember correctly only language runtime images were planned to be added to ubi so this might not work out...

**Comment by phracek** [comment]
@Klaas- Thanks for asking, as far as I know, it was postponed for some reason with uib8 images. I will ask what is progress.

**Comment by phracek** [comment]
The CentOS Stream 8 images are already available by this pull request https://github.com/sclorg/postgresql-container/pull/437

And the images are available on quay.io in this namespace: https://quay.io/organization/sclorg
