### ISSUE TITLE
postgres_1  | createuser: creation of new role failed: ERROR:  role "postgres" already exists

### ISSUE THREAD

**Issue by bscheshirwork** [sclorg/postgresql-container#372]
I have a env 
```
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=fias
```

I got a error
```
postgres_1  | createuser: creation of new role failed: ERROR:  role "postgres" already exists
```

May be we can note about this situation in docs

**Comment by phracek** [comment]
@bscheshirwork Thanks for the report. Good catch. Can you please create a PR with updated documentation? Documentation is available here: https://github.com/sclorg/postgresql-container/blob/master/src/root/usr/share/container-scripts/postgresql/README.md
