### ISSUE TITLE
Build for postgresql-10 and postgresql-12 fails on ppc64le

### ISSUE THREAD

**Issue by seth-priya** [sclorg/postgresql-container#384]
The default centos/s2i-core-centos7 based dockerfile(s) for both versions fail because *rh-postgresql10-runtime* package is missing for ppc64le

Last few lines from the build log
---> Package rh-postgresql10-postgresql.ppc64le 0:10.12-2.el7 will be installed
--> Processing Dependency: rh-postgresql10-runtime for package: rh-postgresql10-postgresql-10.12-2.el7.ppc64le
---> Package rh-postgresql10-postgresql-contrib.ppc64le 0:10.12-2.el7 will be installed
--> Processing Dependency: rh-postgresql10-runtime for package: rh-postgresql10-postgresql-contrib-10.12-2.el7.ppc64le
---> Package rh-postgresql10-postgresql-libs.ppc64le 0:10.12-2.el7 will be installed
--> Processing Dependency: rh-postgresql10-runtime for package: rh-postgresql10-postgresql-libs-10.12-2.el7.ppc64le
Error: Package: rh-postgresql10-postgresql-libs-10.12-2.el7.ppc64le (centos-sclo-rh)
           Requires: rh-postgresql10-runtime
Error: Package: rh-postgresql10-postgresql-10.12-2.el7.ppc64le (centos-sclo-rh)
           Requires: rh-postgresql10-runtime
Error: Package: rh-postgresql10-postgresql-contrib-10.12-2.el7.ppc64le (centos-sclo-rh)
           Requires: rh-postgresql10-runtime
--> Finished Dependency Resolution
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
The command '/bin/sh -c yum install -y centos-release-scl-rh &&     INSTALL_PKGS="rsync tar gettext bind-utils nss_wrapper rh-postgresql10 rh-postgresql10-postgresql-contrib rh-postgresql10-syspaths rh-postgresql96-postgresql-server" &&     yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum -y clean all --enablerepo='*' &&     localedef -f UTF-8 -i en_US en_US.UTF-8 &&     test "$(id postgres)" = "uid=26(postgres) gid=26(postgres) groups=26(postgres)" &&     mkdir -p /var/lib/pgsql/data &&     /usr/libexec/fix-permissions /var/lib/pgsql /var/run/postgresql' returned a non-zero code: 1

any pointers on how to get this package? I could find only an old RPM here https://cbs.centos.org/kojifiles/packages/rh-postgresql10/3.1/1.bs1.el7/

Note that rest of the packages are available and the image should work if "runtime" was as well.

Thanks in advance!

**Comment by seth-priya** [comment]
The image is needed for https://github.com/ManageIQ/container-postgresql/issues/18

**Comment by pkubatrh** [comment]
Hi @seth-priya, unless something changed in the meantime, [we usually do not have SCL builds on architectures other than x86_64 for centos](https://github.com/sclorg/s2i-base-container/issues/178#issuecomment-451379025).
FYI @hhorak @khardix

**Comment by seth-priya** [comment]
thanks @pkubatrh, is there a plan to support it on ppc64le in short/medium term since it seems to work for the most part?

**Comment by khardix** [comment]
@pkubatrh Actually, something has changed in the meantime :) Currently, we should have builds for aarch64 and ppc64le by default for all new builds.

@seth-priya The rh-postgresql10 last build is from before the above change was implemented, so the alternative architecutes are missing. I will try to kick-off the build from them.

As for the rh-postgresql12 in the $subject, [the packages should be already available](https://cbs.centos.org/koji/buildinfo?buildID=27109).

**Comment by seth-priya** [comment]
thanks @khardix that would be really helpful. Yes, I realized that the rh-postgresql12 packages are available but the build of the dockerfile failed for me at this line https://github.com/sclorg/postgresql-container/blob/139dafa98fac426226aff22ab0da4aabbf6e188f/12/Dockerfile#L45 because it installs rh-postgresql10-postgresql-server which again fails for rh-postgresql10-runtime :(

**Comment by pkubatrh** [comment]
>Actually, something has changed in the meantime :) Currently, we should have builds for aarch64 and ppc64le by default for all new builds.

Cool, thanks for the info!

>because it installs rh-postgresql10-postgresql-server which again fails for rh-postgresql10-runtime :(

Technically you could build the version 12 image without the postgresql 10 packages, as those are only used for upgrades from a previous version of the image.

**Comment by seth-priya** [comment]
thanks @pkubatrh for confirming on version 12 image, @khardix is there some place I can subscribe to so that I can be notified once the version 10 builds for Power are available so that I can help validate them and test out ManageIQ/container-postgresql#18 which currently needs 10 as well? thank you!!

**Comment by khardix** [comment]
@seth-priya Turns out I cannot easily "add" the architectures myself, so I opened a CentOS ticket for it: https://pagure.io/centos-infra/issue/73. I will try to reach to you once I have something :slightly_smiling_face:

**Comment by seth-priya** [comment]
@khardix thanks for following through on this, I have subscribed to the above issue as well :)

**Comment by khardix** [comment]
Good news, the rh-postgresql10 altarch packages are now built and should be appearing in repositories shortly (about 24 hours should be plenty of time; if they are still not available after that, let me know).

**Comment by seth-priya** [comment]
thanks @khardix - I will look out for these and test them out once they are available and update here

**Comment by seth-priya** [comment]
@khardix thanks - the packages are now available and I am able to 
- build the postgresql-12 based default (centos) dockerfile on ppc64le without any changes
- build the postgresql-10 based default (centos) dockerfile on ppc64le with a one line change (as expected)

 RUN yum install -y centos-release-scl-rh && \
-    INSTALL_PKGS="rsync tar gettext bind-utils nss_wrapper rh-postgresql10 rh-postgresql10-postgresql-contrib rh-postgresql10-syspaths rh-postgresql96-postgresql-server" && \
+    INSTALL_PKGS="rsync tar gettext bind-utils nss_wrapper rh-postgresql10 rh-postgresql10-postgresql-contrib rh-postgresql10-syspaths" && \

I have been able to validate the basic working of the containers as well

Just had one more questions - are there any plans from your side to publish the multi-arch/ppc64le images to DockerHub?

**Comment by khardix** [comment]
Well, I mostly deal only with the packages, not the containers themselves :slightly_smiling_face: @pkubatrh, any thoughts?

**Comment by pkubatrh** [comment]
Unfortunately we do not have any CI setup for architectures other than x86_64, so no plans to do multiarch pushes to dockerhub in the near future, as having the CI would be a prerequisite.

**Comment by seth-priya** [comment]
Thank you @khardix for you help to make the Power packages available ! @pkubatrh , what CI do you use? we work a lot with TravisCI that is supported on Power today and there are couple of ways with which we can provide Power VMs etc. to run Jenkins if Travis is not an option? I am just trying to understand if this is something I / my team can help with to get it moving forward? your thoughts? (cc @gerrith3)

**Comment by phracek** [comment]
@seth-priya In our CI systems, we use `x86_64` only. And AFAIK we do not plan to support more. All our RHEL images are also tested on different architectures before the release AFAIK.
