### ISSUE TITLE
Add support for PostgreSQL 13

### ISSUE THREAD

**Issue by sellersj** [sclorg/postgresql-container#401]
Current released version of PostgreSQL 13 is 13.2 at this time.

Thanks for your time

**Comment by phracek** [comment]
Postgresql-13 images are already supported. 

CentOS Stream 8: https://quay.io/repository/sclorg/postgresql-13-c8s
CentOS Stream 9: https://quay.io/repository/sclorg/postgresql-13-c9s
Fedora: https://quay.io/repository/fedora/postgresql-13
