### ISSUE TITLE
Where to pull CentOS images from?

### ISSUE THREAD

**Issue by praiskup** [sclorg/postgresql-container#433]
I see this output (example taken from the docs):
```
$ podman pull  centos/postgresql-13-centos7
? Please select an image: 
  ▸ registry.fedoraproject.org/centos/postgresql-13-centos7:latest
    registry.access.redhat.com/centos/postgresql-13-centos7:latest
    docker.io/centos/postgresql-13-centos7:latest
    quay.io/centos/postgresql-13-centos7:latest
```
What variant should I pick?

**Comment by pkubatrh** [comment]
That example is written with dockerhub in mind and should be updated to mirror the move to quay.io. The correct place to get postgresql 13 image is now "quay.io/centos7/postgresql-13-centos7"
