### ISSUE TITLE
OC_ERR: readonly variable

### ISSUE THREAD

**Issue by phracek** [sclorg/postgresql-container#478]
During the nightly build testing I discovered this error:

```bash

OpenShift tests for rhel8/postgresql-12:1 succeeded.
test/test-lib-remote-openshift.sh: line 9: OC_ERR: readonly variable
Setting OCP4 client
PATH /usr/local/oc-v4/bin
Binary oc found in /usr/local/oc-v4/bin
```

**Comment by zmiklank** [comment]
Thanks for the issue, I will look into it.

**Comment by zmiklank** [comment]
The reason of this is, that we source the `test/test-lib-remote-openshift.sh` multiple times during the test execution.
That leads to a situation, that OC_ERR is already set as read only to value 11 when during second source of the `test/test-lib-remote-openshift.sh` the setting fails.

I think we should introduce some mechanism like C header files have to prevent doubled sourcing. WDYT?

**Comment by zmiklank** [comment]
Something like this? https://github.com/sclorg/container-common-scripts

**Comment by zmiklank** [comment]
Fixed by: https://github.com/sclorg/container-common-scripts/pull/309
