### ISSUE TITLE
PostgreSQL 14 support - question

### ISSUE THREAD

**Issue by Victoremepunto** [sclorg/postgresql-container#493]
Hi!

I've seen that on current PRs the test pipelines seem to support PostgreSQL 15 too (i.e. #489) - but there's no mention of PostgreSQL 14 (yet?) .

I'm wondering if support for PostgreSQL 14 is being deferred or skipped for some reason? Our team works using the UBI/RHEL PostgreSQL images for 12 and 13 and are expecting 14 and 15, it'd be great to get some info on the expected release for these PostgreSQL images, if possible.

I've also made a comment on a similar issue #442 to get some feedback there since the issue looked stalled.

Thanks in advance!

**Comment by pkubatrh** [comment]
Hi @Victoremepunto 

For RHEL-based images, there are no plans to ship Postgresql 14 that I know of. It will end up getting skipped similarly to 11 in the past.
Last I checked Fedora had a postgresql 14 module that could be used for an image, but we did not end up adding it as the focus of this repository is on RHEL/Centos Stream images.

Postgresql 15 container image is getting added to the repository in #489 but an official build of the image will need to wait until the underlying RHEL bits get released.

**Comment by hhorak** [comment]
@Victoremepunto would you be interested in Fedora based PostgreSQL 14 image even without plans for having RHEL-based image?

**Comment by bennyturns** [comment]
Yes!  A Fedora base image would work for our use case.

**Comment by Victoremepunto** [comment]
#442 can close this issue . Thanks for the help!
