### ISSUE TITLE
Remove `run_master_restart_test` tests

### ISSUE THREAD

**Issue by phracek** [sclorg/postgresql-container#509]
### Container platform

Podman/Docker

### OS version of the container image

RHEL 8, RHEL 9, CentOS Stream 9

### Description

It looks like the tests `` is failing on several platforms. I would remove it.

See logs here: https://github.com/sclorg/postgresql-container/pull/507
```bash
 [PASSED] for 'postgresql-container_tests' run_replication_test (00:00:06)
 [FAILED] for 'postgresql-container_tests' run_master_restart_test (00:01:13)
 [PASSED] for 'postgresql-container_tests' run_doc_test (00:00:01)
```

**Comment by zmiklank** [comment]
I think that more elaborate explanation on why to remove this test is needed. If we would remove all tests just because they are failing then we do not really need any tests at all.

Could you please explain why specifically this test should be removed instead of being fixed?

**Comment by fila43** [comment]
From my point of view. It tests unsupported functionality. And it would cost a lot of afford to investigate it. I've spent some time debugging it but without any success. It fails randomly. I have some thoughts on catching it, but I am unsure whether it is worth it.

**Comment by zmiklank** [comment]
> From my point of view. It tests unsupported functionality. And it would cost a lot of afford to investigate it. I've spent some time debugging it but without any success. It fails randomly. I have some thoughts on catching it, but I am unsure whether it is worth it.

Hi, thank for your reply. Is there somewhere a list of **supported** functionality? So we could enclose it in the commit message in proceeding PR?

**Comment by phracek** [comment]
This issues is resolved by https://github.com/sclorg/postgresql-container/pull/510. Closing.
