### ISSUE TITLE
latest tag missing from postgresql-12-centos7

### ISSUE THREAD

**Issue by jmontleon** [sclorg/postgresql-container#558]
### Container platform

OCP 4, Podman/Docker

### Version

[postgresql-12-centos7](https://quay.io/repository/centos7/postgresql-12-centos7)

### OS version of the container image

CentOS 7

### Description

We've been pulling the image `quay.io/centos7/postgresql-12-centos7` using the latest tag for quite awhile, but within the last week or so that tag seems to have disappeared. https://quay.io/repository/centos7/postgresql-12-centos7:centos7 and other tags seem to still exist.

### Reproducer

```
$ podman pull quay.io/centos7/postgresql-12-centos7:latest
Trying to pull quay.io/centos7/postgresql-12-centos7:latest...
WARN[0000] Failed, retrying in 1s ... (1/3). Error: initializing source docker://quay.io/centos7/postgresql-12-centos7:latest: reading manifest latest in quay.io/centos7/postgresql-12-centos7: unknown: Tag latest was deleted or has expired. To pull, revive via time machine 
WARN[0002] Failed, retrying in 1s ... (2/3). Error: initializing source docker://quay.io/centos7/postgresql-12-centos7:latest: reading manifest latest in quay.io/centos7/postgresql-12-centos7: unknown: Tag latest was deleted or has expired. To pull, revive via time machine 
WARN[0004] Failed, retrying in 1s ... (3/3). Error: initializing source docker://quay.io/centos7/postgresql-12-centos7:latest: reading manifest latest in quay.io/centos7/postgresql-12-centos7: unknown: Tag latest was deleted or has expired. To pull, revive via time machine 
Error: initializing source docker://quay.io/centos7/postgresql-12-centos7:latest: reading manifest latest in quay.io/centos7/postgresql-12-centos7: unknown: Tag latest was deleted or has expired. To pull, revive via time machine
```

**Comment by kaovilai** [comment]
Tag history suggests it was deleted. https://quay.io/repository/centos7/postgresql-12-centos7?tab=history Wed, Mar 27, 2024 9:44 AM

**Comment by zmiklank** [comment]
Hi, we stopped rebuilding the centos7 sclorg images a long time ago - because the in-this-context-upstream centos7 images stopped the rebuilds too. It no longer holds that sclorg centos7 are "latest", several of them contain vulnerabilities, as they were not rebuilt with fixed rpms.

However, these images are still available at quay.io, but under different tags. Feel free to use them (e.g., with combination with `yum update`), if you consider such image to be appropriate for your use-case.

**Comment by phracek** [comment]
CentOS 7 were completely deprececated. Closing this issue.
