### ISSUE TITLE
Documentation for installing support necessary

### ISSUE THREAD

**Issue by stevekuznetsov** [sclorg/postgresql-container#93]
For instance, when using `uuid-ossp`, the supporting packages need to be installed using `yum` as they are not included in the image normally (maybe they should be? UUID generation is pretty common). The postgres install looks under some `/opt/rh/...` path instead of the normal `/usr/share` path for these files, so layering an image on top of `openshift/postgresql` required a `USER` reset, the installation, and then some symbolic linking. This seems fairly convoluted and was frustrating to work through.

**Comment by praiskup** [comment]
Does `yum install rh-postgresql94-postgresql-contrib -y` help here?

**Comment by stevekuznetsov** [comment]
@praiskup yes, I think that image will be installed correctly and won't require the linking I did. Docs should mention that only the RHSCL RMPs should be installed.

**Comment by praiskup** [comment]
You can install system default packages, too.  But that plugin is not designed to be
run against newer SCL PostgreSQL (9.2 vs 9.4).

Hm, openshift guys think that the fact that SCL packages are actually running inside
image should be hidden as much as possible.  My personal opinion always was
that this is painful and not much useful effort; and hiding something always leads to
misunderstandings.

**Comment by stevekuznetsov** [comment]
I do agree that there is merit to keeping things tidy and hidden under the hood for users that want it to "just work", so I think that if this is our goal we should provide a superset of the resources someone's going to need on a PostgreSQL pod. Having a clear set of instructions for how to layer on top of this image, however, would be useful for those users who are attempting to do something custom. I think many people will consume this image as a "trusted RH image distribution" and won't be quick to start altering it, as that breaks the whole premise for its existence.
