### ISSUE TITLE
postgresql version 9.5 required

### ISSUE THREAD

**Issue by deswaraj** [sclorg/postgresql-container#95]
postgresql 9.5 have major changes please consider to build a cartridge 

http://www.postgresql.org/about/featurematrix/

**Comment by praiskup** [comment]
This could be closed, there is openshift/postgresql/issues/95.

**Comment by pkajaba** [comment]
You might want to add this link https://github.com/openshift/postgresql/pull/99

**Comment by praiskup** [comment]
yes :)

**Comment by deswaraj** [comment]
I have some urgency in my job.Can you please let me know how long it may take ?

Thanks..

**Comment by mnagy** [comment]
@pkajaba ping, do you know the answer to @deswaraj's question?

**Comment by praiskup** [comment]
@mnagy, I don't think we know the answer ATM, @hhorak?

**Comment by hhorak** [comment]
@deswaraj I'd like to answer, but I'm not sure what is the question. Do you ask for CentOS or RHEL image for PostgreSQL 9.5? Or anything else?

**Comment by mnagy** [comment]
@hhorak this is waiting for #99 which hangs on https://github.com/openshift/postgresql/pull/99#issuecomment-186388043

**Comment by hhorak** [comment]
As I wrote in #99, we have some testing packages for CentOS already, but there won't be any for RHEL for some time still (several weeks). I'm sorry that I cannot give any specific dates.

**Comment by deswaraj** [comment]
@hhorak I want PostgreSQL version 9.5 cartridge to host with open shift.

**Comment by mnagy** [comment]
@hhorak are the CentOS packages released yet, or do RHEL packages need to go out first? If they are available, maybe @pkajaba could update #99 with a CentOS Dockerfile so @deswaraj can at least try to build his own..?

**Comment by hhorak** [comment]
@mnagy CentOS packages will be testing quality only and also available in testing repository only until RHSCL packages are released.

**Comment by mfojtik** [comment]
@deswaraj are you referring to openshift v2 or openshift v3?

**Comment by deswaraj** [comment]
openshift v3

**Comment by pkajaba** [comment]
Hello, you can try dockerfiles from there #99 : you are probably interested in Dockerfile-beta. Just rename it to Dockerfile and you can build with make TARGET=centos7 VERSION=9.5

**Comment by hhorak** [comment]
We can close this since 9.5 is already part of this repo.
